// Generated by oagen. DO NOT EDIT.


import type { BaseClient } from '../_baseClient.js';
import type { HealthResponse } from '../_models.js';

/** Healthz resource. */
export class Healthz {
  constructor(private readonly client: BaseClient) {}

  /**
   * Health check
   *
   * Returns health status of the service
   */
  async healthCheck(): Promise<HealthResponse> {
    return this.client.request<HealthResponse>({
      method: 'GET',
      path: '/healthz',
    });
  }
}
