// Generated by oagen. DO NOT EDIT.


import type { BaseClient } from '../_baseClient.js';
import type { ReadinessResponse } from '../_models.js';

/** Readyz resource. */
export class Readyz {
  constructor(private readonly client: BaseClient) {}

  /**
   * Readiness check
   *
   * Returns readiness status with active sandbox count
   */
  async readinessCheck(): Promise<ReadinessResponse> {
    return this.client.request<ReadinessResponse>({
      method: 'GET',
      path: '/readyz',
    });
  }
}
