// Generated by oagen. DO NOT EDIT.


import type { BaseClient } from '../_baseClient.js';
import type { CountResponse, CreateResponse, ExecRequest, ExecResponse, ListResponse, LogsResponse, LookupResult, SandboxSpec, StatusResponse } from '../_models.js';
import type { SandboxesPhase } from '../enums.js';

/** Sandboxes resource. */
export class Sandboxes {
  constructor(private readonly client: BaseClient) {}

  /**
   * List sandboxes
   *
   * List sandboxes, optionally filtered by name prefix, exact tag, phase, or image.
   */
  async list(options?: { startTime?: string; endTime?: string; search?: string; tag?: string[]; phase?: SandboxesPhase[]; image?: string; includeFilterValues?: boolean; page?: number }): Promise<ListResponse> {
    return this.client.request<ListResponse>({
      method: 'GET',
      path: '/v1/sandbox',
      query: { start_time: options?.startTime, end_time: options?.endTime, search: options?.search, tag: options?.tag, phase: options?.phase, image: options?.image, include_filter_values: options?.includeFilterValues, page: options?.page },
    });
  }

  /**
   * Count sandboxes over time
   *
   * Count sandboxes by creation time, bucketed over a window, using the same
   * filters as the list endpoint. Covers only sandboxes the control plane
   * still retains.
   */
  async counts(options?: { startTime?: string; endTime?: string; search?: string; tag?: string[]; phase?: SandboxesPhase[]; image?: string }): Promise<CountResponse> {
    return this.client.request<CountResponse>({
      method: 'GET',
      path: '/v1/sandbox/counts',
      query: { start_time: options?.startTime, end_time: options?.endTime, search: options?.search, tag: options?.tag, phase: options?.phase, image: options?.image },
    });
  }

  /**
   * Create sandbox
   *
   * Create a new sandbox and queue it for execution
   */
  async create(body: SandboxSpec): Promise<CreateResponse> {
    return this.client.request<CreateResponse>({
      method: 'POST',
      path: '/v1/sandbox/run',
      body,
    });
  }

  /**
   * Resolve a sandbox name to its id
   *
   * Resolve a sandbox name to its id. Names are unique, so this returns at
   * most one id. All other sandbox operations address the sandbox by id.
   */
  async lookup(options: { name: string }): Promise<LookupResult> {
    return this.client.request<LookupResult>({
      method: 'GET',
      path: '/v1/sandbox/lookup',
      query: { name: options.name },
    });
  }

  /**
   * Get sandbox status
   *
   * Get the current status of a sandbox
   */
  async get(id: string): Promise<StatusResponse> {
    return this.client.request<StatusResponse>({
      method: 'GET',
      path: `/v1/sandbox/${id}`,
    });
  }

  /**
   * Terminate sandbox
   *
   * Terminate a sandbox and clean up its resources
   */
  async delete(id: string): Promise<void> {
    return this.client.request<void>({
      method: 'DELETE',
      path: `/v1/sandbox/${id}`,
    });
  }

  /**
   * Get sandbox logs
   *
   * Get logs from a sandbox via Loki. Logs persist after sandbox termination.
   */
  async getLogs(id: string, options?: { limit?: number; since?: string }): Promise<LogsResponse> {
    return this.client.request<LogsResponse>({
      method: 'GET',
      path: `/v1/sandbox/${id}/logs`,
      query: { limit: options?.limit, since: options?.since },
    });
  }

  /**
   * Exec in sandbox
   *
   * Run a command in a running sandbox and return its output and exit code
   */
  async exec(id: string, body: ExecRequest): Promise<ExecResponse> {
    return this.client.request<ExecResponse>({
      method: 'POST',
      path: `/v1/sandbox/${id}/exec`,
      body,
    });
  }
}
