// Generated by oagen. DO NOT EDIT.


import type { BaseClient } from '../_baseClient.js';
import type { Snapshot, SnapshotListResponse, SnapshotSpec } from '../_models.js';

/** Snapshots resource. */
export class Snapshots {
  constructor(private readonly client: BaseClient) {}

  /**
   * Snapshot a sandbox
   *
   * Capture a running sandbox so a new sandbox can be started from it later.
   * The sandbox keeps running.
   */
  async create(id: string, body: SnapshotSpec): Promise<Snapshot> {
    return this.client.request<Snapshot>({
      method: 'POST',
      path: `/v1/sandbox/${id}/snapshot`,
      body,
    });
  }

  /**
   * List snapshots
   *
   * List captured snapshots, most recent first.
   */
  async list(options?: { sandboxId?: string }): Promise<SnapshotListResponse> {
    return this.client.request<SnapshotListResponse>({
      method: 'GET',
      path: '/v1/snapshot',
      query: { sandbox_id: options?.sandboxId },
    });
  }

  /**
   * Delete snapshot
   *
   * Delete a snapshot and everything it captured.
   */
  async delete(id: string): Promise<void> {
    return this.client.request<void>({
      method: 'DELETE',
      path: `/v1/snapshot/${id}`,
    });
  }
}
