// Generated by oagen. DO NOT EDIT.


import type { BaseClient } from '../_baseClient.js';
import type { LookupResult, Volume, VolumeListResponse, VolumeSpec } from '../_models.js';

/** Volumes resource. */
export class Volumes {
  constructor(private readonly client: BaseClient) {}

  /**
   * List volumes
   *
   * List volumes and the sandboxes they are attached to.
   */
  async list(): Promise<VolumeListResponse> {
    return this.client.request<VolumeListResponse>({
      method: 'GET',
      path: '/v1/volume',
    });
  }

  /**
   * Create volume
   *
   * Create a persistent volume that sandboxes can mount at launch
   */
  async create(body: VolumeSpec): Promise<Volume> {
    return this.client.request<Volume>({
      method: 'POST',
      path: '/v1/volume',
      body,
    });
  }

  /**
   * Resolve a volume name to its id
   *
   * Resolve a volume name to its id. Names are unique, so this returns at
   * most one id. All other volume operations address the volume by id.
   */
  async lookup(options: { name: string }): Promise<LookupResult> {
    return this.client.request<LookupResult>({
      method: 'GET',
      path: '/v1/volume/lookup',
      query: { name: options.name },
    });
  }

  /**
   * Get volume
   *
   * Get a volume and the sandboxes it is attached to
   */
  async get(id: string): Promise<Volume> {
    return this.client.request<Volume>({
      method: 'GET',
      path: `/v1/volume/${id}`,
    });
  }

  /**
   * Delete volume
   *
   * Delete a volume. Fails while the volume is attached to a sandbox.
   */
  async delete(id: string): Promise<void> {
    return this.client.request<void>({
      method: 'DELETE',
      path: `/v1/volume/${id}`,
    });
  }
}
