// Generated by oagen. DO NOT EDIT.


import type { BaseClient, BinaryBody, BinaryContent } from '../_baseClient.js';
import type { LookupResult, Volume, VolumeFileListResponse, VolumeFileMoveRequest, VolumeListResponse, VolumeSpec } from '../_models.js';

/** Volumes resource. */
export class Volumes {
  constructor(private readonly client: BaseClient) {}

  /**
   * List volumes
   *
   * List volumes and the sandboxes they are attached to.
   */
  async list(): Promise<VolumeListResponse> {
    return this.client.request<VolumeListResponse>({
      method: 'GET',
      path: '/v1/volume',
    });
  }

  /**
   * Create volume
   *
   * Create a persistent volume that sandboxes can mount at launch
   */
  async create(body: VolumeSpec): Promise<Volume> {
    return this.client.request<Volume>({
      method: 'POST',
      path: '/v1/volume',
      body,
    });
  }

  /**
   * Resolve a volume name to its id
   *
   * Resolve a volume name to its id. Names are unique, so this returns at
   * most one id. All other volume operations address the volume by id.
   */
  async lookup(options: { name: string }): Promise<LookupResult> {
    return this.client.request<LookupResult>({
      method: 'GET',
      path: '/v1/volume/lookup',
      query: { name: options.name },
    });
  }

  /**
   * Get volume
   *
   * Get a volume and the sandboxes it is attached to
   */
  async get(id: string): Promise<Volume> {
    return this.client.request<Volume>({
      method: 'GET',
      path: `/v1/volume/${id}`,
    });
  }

  /**
   * Delete volume
   *
   * Delete a volume. Fails while the volume is attached to a sandbox.
   */
  async delete(id: string): Promise<void> {
    return this.client.request<void>({
      method: 'DELETE',
      path: `/v1/volume/${id}`,
    });
  }

  /**
   * List volume files
   *
   * List the files and directories under a path inside a volume, read from
   * the shared sandbox volumes mount. The listing walks the tree
   * breadth-first up to a server-side entry budget: small trees come back
   * complete in one response, and directories the walk did not fully read
   * are marked truncated for clients to list directly. Requires the control
   * plane to have the mount configured; without it every listing reports
   * the files API as unavailable.
   */
  async listFiles(id: string, options?: { path?: string; search?: string }): Promise<VolumeFileListResponse> {
    return this.client.request<VolumeFileListResponse>({
      method: 'GET',
      path: `/v1/volume/${id}/files`,
      query: { path: options?.path, search: options?.search },
    });
  }

  /**
   * Read volume file
   *
   * Stream a file's raw bytes from a volume. The response is the file
   * content itself, so clients bound how much they read: send a single
   * byte range (e.g. bytes=0-1048575) to read part of the file, or omit
   * the Range header for the whole file.
   */
  async readFile(id: string, options: { path: string; range?: string }, requestOptions?: { timeoutMs?: number }): Promise<BinaryContent> {
    return this.client.requestBinary({
      method: 'GET',
      path: `/v1/volume/${id}/files/content`,
      query: { path: options.path },
      headers: { Range: options.range },
      timeoutMs: requestOptions?.timeoutMs ?? null,
    });
  }

  /**
   * Write volume file
   *
   * Write a file to a volume, replacing whatever is at the path and creating
   * parent directories as needed. The request body is the file's raw bytes,
   * of any size. The write is only visible at the path once the whole body
   * has been received, so an upload that fails partway leaves the previous
   * content in place rather than a truncated file.
   */
  async writeFile(id: string, body: BinaryBody, options: { path: string }, requestOptions?: { timeoutMs?: number }): Promise<void> {
    return this.client.request<void>({
      method: 'PUT',
      path: `/v1/volume/${id}/files/content`,
      query: { path: options.path },
      body,
      bodyContentType: 'application/octet-stream',
      timeoutMs: requestOptions?.timeoutMs ?? null,
    });
  }

  /**
   * Move volume file
   *
   * Move or rename a file or directory inside a volume. The destination is
   * the entry's full new path, so one call covers both renaming in place and
   * relocating into another directory, and a directory moves with everything
   * under it. The destination's parent directory must already exist, and a
   * move onto a path something is already at is refused rather than
   * overwriting it.
   */
  async moveFile(id: string, body: VolumeFileMoveRequest): Promise<void> {
    return this.client.request<void>({
      method: 'POST',
      path: `/v1/volume/${id}/files/move`,
      body,
    });
  }
}
