// Generated by oagen. DO NOT EDIT.


import { describe, expect, it } from 'vitest';
import type { CountPoint, CountResponse, CreateResponse, Error, ExecRequest, ExecResponse, ExecTarget, FilterValuesResponse, HealthResponse, LogsResponse, LookupResult, Pagination, ReadinessResponse, SandboxDomainSpec, SandboxEgressSpec, SandboxNetworkingSpec, SandboxSpec, VolumeFileListResponse, VolumeListResponse, VolumeSpec } from '../src/_models.js';

describe('model round trip', () => {
  it('accepts a structurally valid CountPoint', () => {
    const value: CountPoint = {
      timestamp: 'x',
      count: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CountPoint;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid CountResponse', () => {
    const value: CountResponse = {
      points: [],
      granularity_ms: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CountResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid CreateResponse', () => {
    const value: CreateResponse = {
      id: 'x',
      name: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CreateResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid Error', () => {
    const value: Error = {
      error: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as Error;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecRequest', () => {
    const value: ExecRequest = {
      command: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecRequest;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecResponse', () => {
    const value: ExecResponse = {
      stdout: 'x',
      stderr: 'x',
      exit_code: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecTarget', () => {
    const value: ExecTarget = {
      namespace: 'x',
      pod_name: 'x',
      container_name: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecTarget;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid FilterValuesResponse', () => {
    const value: FilterValuesResponse = {
      tags: [],
      images: [],
      phases: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as FilterValuesResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid HealthResponse', () => {
    const value: HealthResponse = {
      status: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as HealthResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid LogsResponse', () => {
    const value: LogsResponse = {
      sandbox_id: 'x',
      logs: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as LogsResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid LookupResult', () => {
    const value: LookupResult = {
      id: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as LookupResult;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid Pagination', () => {
    const value: Pagination = {
      current_page: 1,
      total_pages: 1,
      has_next_page: true,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as Pagination;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ReadinessResponse', () => {
    const value: ReadinessResponse = {
      status: 'x',
      active_sandboxes: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ReadinessResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxDomainSpec', () => {
    const value: SandboxDomainSpec = {};
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxDomainSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxEgressSpec', () => {
    const value: SandboxEgressSpec = {
      allowed_destinations: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxEgressSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxNetworkingSpec', () => {
    const value: SandboxNetworkingSpec = {
      port: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxNetworkingSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxSpec', () => {
    const value: SandboxSpec = {
      image: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeFileListResponse', () => {
    const value: VolumeFileListResponse = {
      path: 'x',
      entries: [],
      truncated: true,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeFileListResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeListResponse', () => {
    const value: VolumeListResponse = {
      volumes: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeListResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeSpec', () => {
    const value: VolumeSpec = {};
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeSpec;
    expect(roundTripped).toEqual(value);
  });
});
