// Generated by oagen. DO NOT EDIT.


import { describe, expect, it } from 'vitest';
import type { CountPoint, CountResponse, CreateResponse, Error, ExecRequest, ExecResponse, ExecTarget, FilterValuesResponse, HealthResponse, LogsResponse, LookupResult, MetricSummaryResponse, Pagination, ReadinessResponse, SandboxDomainSpec, SandboxEgressSpec, SandboxMetricsPoint, SandboxMetricsResponse, SandboxMetricsResult, SandboxMetricsSeries, SandboxNetworkingSpec, SandboxResourcesSpec, SandboxSpec, VolumeFileListResponse, VolumeFileMoveRequest, VolumeListResponse, VolumeObjectSpec, VolumeSpec } from '../src/_models.js';

describe('model round trip', () => {
  it('accepts a structurally valid CountPoint', () => {
    const value: CountPoint = {
      timestamp: 'x',
      count: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CountPoint;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid CountResponse', () => {
    const value: CountResponse = {
      points: [],
      granularity_ms: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CountResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid CreateResponse', () => {
    const value: CreateResponse = {
      id: 'x',
      name: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as CreateResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid Error', () => {
    const value: Error = {
      error: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as Error;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecRequest', () => {
    const value: ExecRequest = {
      command: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecRequest;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecResponse', () => {
    const value: ExecResponse = {
      stdout: 'x',
      stderr: 'x',
      exit_code: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ExecTarget', () => {
    const value: ExecTarget = {
      namespace: 'x',
      pod_name: 'x',
      container_name: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ExecTarget;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid FilterValuesResponse', () => {
    const value: FilterValuesResponse = {
      tags: [],
      images: [],
      phases: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as FilterValuesResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid HealthResponse', () => {
    const value: HealthResponse = {
      status: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as HealthResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid LogsResponse', () => {
    const value: LogsResponse = {
      sandbox_id: 'x',
      logs: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as LogsResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid LookupResult', () => {
    const value: LookupResult = {
      id: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as LookupResult;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid MetricSummaryResponse', () => {
    const value: MetricSummaryResponse = {
      window_seconds: 1,
      has_data: true,
      cpu_cores_p50: 1,
      cpu_cores_p90: 1,
      cpu_limit_cores: 1,
      cpu_util_p50_pct: 1,
      cpu_util_p90_pct: 1,
      mem_bytes_p50: 1,
      mem_bytes_p90: 1,
      mem_limit_bytes: 1,
      mem_util_p50_pct: 1,
      mem_util_p90_pct: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as MetricSummaryResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid Pagination', () => {
    const value: Pagination = {
      current_page: 1,
      total_pages: 1,
      has_next_page: true,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as Pagination;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid ReadinessResponse', () => {
    const value: ReadinessResponse = {
      status: 'x',
      active_sandboxes: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as ReadinessResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxDomainSpec', () => {
    const value: SandboxDomainSpec = {};
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxDomainSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxEgressSpec', () => {
    const value: SandboxEgressSpec = {
      allowed_destinations: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxEgressSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxMetricsPoint', () => {
    const value: SandboxMetricsPoint = {
      timestamp_utc: 'x',
      value: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxMetricsPoint;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxMetricsResponse', () => {
    const value: SandboxMetricsResponse = {
      results: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxMetricsResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxMetricsResult', () => {
    const value: SandboxMetricsResult = {
      series: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxMetricsResult;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxMetricsSeries', () => {
    const value: SandboxMetricsSeries = {
      time_series: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxMetricsSeries;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxNetworkingSpec', () => {
    const value: SandboxNetworkingSpec = {
      port: 1,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxNetworkingSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxResourcesSpec', () => {
    const value: SandboxResourcesSpec = {};
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxResourcesSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid SandboxSpec', () => {
    const value: SandboxSpec = {
      image: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as SandboxSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeFileListResponse', () => {
    const value: VolumeFileListResponse = {
      path: 'x',
      entries: [],
      truncated: true,
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeFileListResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeFileMoveRequest', () => {
    const value: VolumeFileMoveRequest = {
      from: 'x',
      to: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeFileMoveRequest;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeListResponse', () => {
    const value: VolumeListResponse = {
      volumes: [],
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeListResponse;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeObjectSpec', () => {
    const value: VolumeObjectSpec = {
      bucket: 'x',
    };
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeObjectSpec;
    expect(roundTripped).toEqual(value);
  });

  it('accepts a structurally valid VolumeSpec', () => {
    const value: VolumeSpec = {};
    const roundTripped = JSON.parse(JSON.stringify(value)) as VolumeSpec;
    expect(roundTripped).toEqual(value);
  });
});
