// Generated by oagen. DO NOT EDIT.


import { errorForStatus, SandboxError, SandboxTimeoutError } from './_errors.js';
import { resolveConfig, type Config, type ConfigInput } from './_config.js';
import { DEFAULT_MAX_RETRIES, shouldRetry, sleepForAttempt } from './_retries.js';

const USER_AGENT = 'porter-sandbox-typescript/0.0.1';

export interface ClientOptions extends ConfigInput {
  maxRetries?: number;
}

export interface RequestOptions {
  method: string;
  path: string;
  query?: Record<string, unknown> | undefined;
  headers?: Record<string, string | undefined> | undefined;
  body?: unknown;
  // Set for a byte-bodied endpoint. The body goes out as-is under this content
  // type.
  bodyContentType?: string | undefined;
  // Per-request timeout. `null` disables it, for a call the API works on for the
  // full duration of the request. Omitted means the client-wide default.
  timeoutMs?: number | null | undefined;
  // Set false for calls that must not be re-sent (exec): a failed attempt may
  // have executed server-side, so retrying could run the command again.
  retry?: boolean | undefined;
}

/** A byte range within a file, read back from a response's Content-Range header. */
export interface ContentRange {
  start: number;
  end: number;
  size: number;
}

/** Raw bytes from an octet-stream endpoint, with the metadata needed to read a file in pieces. */
export interface BinaryContent {
  bytes: Uint8Array;
  // Which bytes of the file arrived and how large the file is, set when the
  // request asked for a range.
  contentRange: ContentRange | null;
  lastModified: Date | null;
}

// HTTP transport shared by the generated resource classes. Owns auth/header
// injection, the retry loop, and error mapping. Resource methods call
// `this.client.request<T>(...)`, or `requestBinary(...)` for the endpoints
// that answer with bytes rather than JSON.
export class BaseClient {
  private readonly config: Config;
  private readonly maxRetries: number;

  constructor(options: ClientOptions = {}) {
    const { maxRetries, ...configInput } = options;
    this.config = resolveConfig(configInput);
    this.maxRetries = maxRetries ?? DEFAULT_MAX_RETRIES;
  }

  close(): void {
    // fetch has no persistent connection pool to close in standard Node 18+
    // runtime; method exists so callers can model lifecycle symmetry.
  }

  async request<T>(options: RequestOptions): Promise<T> {
    const response = await this.send(options, 'application/json');
    return (await decodeBody(response)) as T;
  }

  async requestBinary(options: RequestOptions): Promise<BinaryContent> {
    const response = await this.send(options, 'application/octet-stream');
    const buffer = await response.arrayBuffer();
    return {
      bytes: new Uint8Array(buffer),
      contentRange: parseContentRange(response.headers.get('content-range')),
      lastModified: parseHttpDate(response.headers.get('last-modified')),
    };
  }

  // Runs the request through the retry loop and hands back the successful
  // response with its body unread, so callers decode it as JSON or as bytes.
  private async send(options: RequestOptions, accept: string): Promise<Response> {
    const url = buildUrl(this.config.baseUrl, options.path, options.query);
    const init = buildInit(this.config, options, accept);
    const timeoutMs = options.timeoutMs === undefined ? this.config.timeoutMs : options.timeoutMs;
    const maxRetries = options.retry === false ? 0 : this.maxRetries;

    let lastError: unknown = null;

    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      let response: Response;
      try {
        response = await withTimeout(fetch(url, init), timeoutMs);
      } catch (err) {
        // A timed-out request may have executed server-side, so retrying
        // could run it again. Surface the timeout instead.
        if (err instanceof SandboxTimeoutError) throw err;
        lastError = err;
        if (attempt < maxRetries) {
          await sleepForAttempt(attempt);
          continue;
        }
        throw new SandboxError(`Network error: ${describeError(err)}`);
      }

      if (response.status >= 200 && response.status < 300) return response;

      if (shouldRetry(response.status) && attempt < maxRetries) {
        await sleepForAttempt(attempt);
        continue;
      }

      const body = await decodeBody(response);
      throw errorForStatus(response.status, body, errorMessage(body, response.status));
    }

    throw new SandboxError(`Request failed after retries: ${describeError(lastError)}`);
  }
}

export const buildUrl = (baseUrl: string, path: string, query: Record<string, unknown> | undefined): string => {
  // Concatenate rather than `new URL(path, base)`: a leading-slash path is an
  // absolute reference, so `new URL` would discard any path prefix on the base
  // (e.g. the Porter gateway base `…/projects/1/clusters/2` that _config
  // builds from the API token) and resolve to `https://host/v1/sandbox/run`.
  // Joining the strings keeps the prefix, so the same client works whether it
  // points straight at the in-cluster sandbox-api or through the Porter API.
  const url = new URL(`${baseUrl.replace(/\/$/, '')}${path}`);
  if (query) {
    for (const [key, value] of Object.entries(query)) {
      if (value === undefined || value === null) continue;
      if (Array.isArray(value)) {
        for (const v of value) url.searchParams.append(key, String(v));
      } else {
        url.searchParams.set(key, String(value));
      }
    }
  }
  return url.toString();
};

const buildInit = (config: Config, options: RequestOptions, accept: string): RequestInit => {
  const headers: Record<string, string> = {
    'User-Agent': USER_AGENT,
    Accept: accept,
  };
  if (config.apiKey) {
    headers.Authorization = `Bearer ${config.apiKey}`;
  }
  for (const [name, value] of Object.entries(options.headers ?? {})) {
    if (value !== undefined) headers[name] = value;
  }
  if (options.body === undefined) {
    return { method: options.method, headers };
  }

  // A byte body goes out untouched, and anything else is JSON. Content-Type is
  // set alongside the body so the two agree.
  headers['Content-Type'] = options.bodyContentType ?? 'application/json';
  // A retry re-sends this body, so fetch must be able to read it twice. The
  // byte-bodied methods take a Uint8Array for that reason.
  const body = options.bodyContentType === undefined ? JSON.stringify(options.body) : (options.body as Uint8Array);
  return { method: options.method, headers, body };
};

const withTimeout = <T>(promise: Promise<T>, timeoutMs: number | null): Promise<T> => {
  // `null` disables the timeout: the caller waits as long as the request runs.
  if (timeoutMs === null) return promise;
  // AbortController would be cleaner, but fetch in older Node 18 had spotty
  // signal support. setTimeout+race is universally supported and keeps the
  // pending fetch from leaking once we've already given up.
  let timer: NodeJS.Timeout | undefined;
  const timeout = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new SandboxTimeoutError(`request timed out after ${timeoutMs}ms`)), timeoutMs);
  });
  return Promise.race([promise, timeout]).finally(() => {
    if (timer) clearTimeout(timer);
  });
};

const decodeBody = async (response: Response): Promise<unknown> => {
  if (response.status === 204) return null;
  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.includes('application/json')) {
    const text = await response.text();
    if (!text) return null;
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }
  return response.text();
};

// `bytes 0-1023/8192`. Absent on a whole-file response.
const CONTENT_RANGE_RE = /^bytes (\d+)-(\d+)\/(\d+)$/;

export const parseContentRange = (header: string | null): ContentRange | null => {
  const match = header?.match(CONTENT_RANGE_RE);
  if (!match) return null;
  return { start: Number(match[1]), end: Number(match[2]), size: Number(match[3]) };
};

const parseHttpDate = (header: string | null): Date | null => {
  if (!header) return null;
  const date = new Date(header);
  return Number.isNaN(date.getTime()) ? null : date;
};

const errorMessage = (body: unknown, statusCode: number): string => {
  if (body && typeof body === 'object' && 'error' in body && typeof body.error === 'string') {
    return body.error;
  }
  return `HTTP ${statusCode}`;
};

const describeError = (err: unknown): string =>
  err instanceof Error ? err.message : String(err);
