// Generated by oagen. DO NOT EDIT.


import { BaseClient, type ClientOptions } from './_baseClient.js';
import { Healthz } from './resources/healthz.js';
import { Readyz } from './resources/readyz.js';
import { Sandboxes } from './resources/sandboxes.js';
import { Volumes } from './resources/volumes.js';

/** Low-level client for the Porter sandbox API. */
export class PorterSandboxApiClient {
  private readonly base: BaseClient;

  readonly healthz: Healthz;
  readonly readyz: Readyz;
  readonly sandboxes: Sandboxes;
  readonly volumes: Volumes;

  constructor(options: ClientOptions = {}) {
    this.base = new BaseClient(options);
    this.healthz = new Healthz(this.base);
    this.readyz = new Readyz(this.base);
    this.sandboxes = new Sandboxes(this.base);
    this.volumes = new Volumes(this.base);
  }

  close(): void {
    this.base.close();
  }
}
