// Generated by oagen. DO NOT EDIT.


// Base class for all Porter sandbox SDK errors.
export class SandboxError extends Error {
  readonly statusCode: number | null;
  readonly body: unknown;

  constructor(message: string, options: { statusCode?: number; body?: unknown } = {}) {
    super(message);
    this.name = 'SandboxError';
    this.statusCode = options.statusCode ?? null;
    this.body = options.body ?? null;
  }
}

// Raised when the API rejects credentials (401).
export class AuthenticationError extends SandboxError {
  constructor(message: string, options: { statusCode?: number; body?: unknown } = {}) {
    super(message, options);
    this.name = 'AuthenticationError';
  }
}

// Raised when a sandbox or other resource cannot be found (404).
export class NotFoundError extends SandboxError {
  constructor(message: string, options: { statusCode?: number; body?: unknown } = {}) {
    super(message, options);
    this.name = 'NotFoundError';
  }
}

// Raised when the API responds with 429 Too Many Requests.
export class RateLimitError extends SandboxError {
  constructor(message: string, options: { statusCode?: number; body?: unknown } = {}) {
    super(message, options);
    this.name = 'RateLimitError';
  }
}

// Raised on 5xx responses from the API.
export class ServerError extends SandboxError {
  constructor(message: string, options: { statusCode?: number; body?: unknown } = {}) {
    super(message, options);
    this.name = 'ServerError';
  }
}

// Raised when a request exceeds its timeout. Never retried by the client: the
// server may still be executing the request (e.g. a long-running exec), so a
// retry could run it again.
export class SandboxTimeoutError extends SandboxError {
  constructor(message: string) {
    super(message);
    this.name = 'SandboxTimeoutError';
  }
}

// Map an HTTP status code to the appropriate SandboxError subclass.
export const errorForStatus = (
  statusCode: number,
  body: unknown,
  message: string,
): SandboxError => {
  const options = { statusCode, body };
  if (statusCode === 401) return new AuthenticationError(message, options);
  if (statusCode === 404) return new NotFoundError(message, options);
  if (statusCode === 429) return new RateLimitError(message, options);
  if (statusCode >= 500 && statusCode < 600) return new ServerError(message, options);
  return new SandboxError(message, options);
};
