// Generated by oagen. DO NOT EDIT.


import type { FilterValuesResponsePhases, LogLineLevel, SandboxDomainSpecVisibility, SnapshotMode, SnapshotStatus, StatusResponsePhase, VolumeFileEntryType, VolumeObjectSpecAccess, VolumePhase, VolumeSpecType, VolumeType } from './enums.js';

export interface CountPoint {
  /** Start of the bucket. */
  timestamp: string;
  /** Sandboxes created within the bucket. */
  count: number;
}

export interface CountResponse {
  /** Created-sandbox counts per bucket, oldest first, gap-free. */
  points: CountPoint[];
  /** Width of each bucket in milliseconds. */
  granularity_ms: number;
}

export interface CreateResponse {
  /** Sandbox ID */
  id: string;
  /** Sandbox name (the id when no name was given) */
  name: string;
  /** Volumes the sandbox mounts, keyed by mount path */
  volume_mounts?: Record<string, string>;
}

export interface Error {
  /** Error message */
  error: string;
}

export interface ExecRequest {
  /** Command and arguments to run in the sandbox */
  command: string[];
}

export interface ExecResponse {
  /** Captured standard output */
  stdout: string;
  /** Captured standard error */
  stderr: string;
  /** Command exit code. Non-zero is a normal result, not an error. */
  exit_code: number;
}

export interface ExecTarget {
  /** Namespace of the sandbox pod */
  namespace: string;
  /** Name of the sandbox pod */
  pod_name: string;
  /** Container to target. For warm sandboxes this is the pod's placeholder container, which the node redirects to the injected workload. */
  container_name: string;
}

export interface FilterValuesResponse {
  /** Distinct sandbox tags, formatted as key=value */
  tags: string[];
  /** Distinct sandbox images */
  images: string[];
  /** Supported sandbox phases */
  phases: FilterValuesResponsePhases[];
}

export interface HealthResponse {
  /** Health status */
  status: string;
}

export interface ListResponse {
  /** Matching sandboxes */
  sandboxes: StatusResponse[];
  pagination: Pagination;
  /** Cluster-wide filter option values, included only when requested. */
  filter_values?: FilterValuesResponse;
}

export interface LogLine {
  /** When the log line was emitted */
  timestamp: string;
  /** Log line content */
  line: string;
  /** Log severity level */
  level: LogLineLevel;
  /** ID of the exec that produced this line; empty when the line is the workload's own output */
  exec_id: string;
}

export interface LogsResponse {
  /** Sandbox ID */
  sandbox_id: string;
  /** Log lines */
  logs: LogLine[];
}

export interface LookupResult {
  /** The resolved resource id */
  id: string;
}

/** p50/p90 CPU and memory usage over a lookback window with utilization against the sandbox's limits. Memory values include page cache, so they slightly overestimate resident memory. */
export interface MetricSummaryResponse {
  /** Lookback window the summary was computed over. */
  window_seconds: number;
  /**
   * False when Prometheus returned no series for the sandbox's pod, which
   * happens for freshly-started sandboxes (Prometheus scrapes at ~1m) and
   * for pods shorter-lived than the [3m, 24h] window. When false, callers
   * should render "no data yet" rather than the zeroed metric fields.
   */
  has_data: boolean;
  /** 50th percentile CPU usage in cores. */
  cpu_cores_p50: number;
  /** 90th percentile CPU usage in cores. */
  cpu_cores_p90: number;
  /** CPU limit configured on the sandbox pod, in cores. Zero when no limit is set. */
  cpu_limit_cores: number;
  /** p50 CPU usage as a percentage of the CPU limit. Zero when no limit is set. */
  cpu_util_p50_pct: number;
  /** p90 CPU usage as a percentage of the CPU limit. Zero when no limit is set. */
  cpu_util_p90_pct: number;
  /** 50th percentile memory usage in bytes. Includes page cache. */
  mem_bytes_p50: number;
  /** 90th percentile memory usage in bytes. Includes page cache. */
  mem_bytes_p90: number;
  /** Memory limit configured on the sandbox pod, in bytes. Zero when no limit is set. */
  mem_limit_bytes: number;
  /** p50 memory usage as a percentage of the memory limit. Zero when no limit is set. */
  mem_util_p50_pct: number;
  /** p90 memory usage as a percentage of the memory limit. Zero when no limit is set. */
  mem_util_p90_pct: number;
}

export interface Pagination {
  /** Current page number (1-based) */
  current_page: number;
  /** Total number of pages */
  total_pages: number;
  /** Whether there are more items after this page */
  has_next_page: boolean;
}

export interface ReadinessResponse {
  /** Readiness status */
  status: string;
  /** Number of active sandboxes */
  active_sandboxes: number;
}

export interface SandboxDomainSpec {
  /**
   * Fully qualified hostname for the sandbox, one label under the
   * target ingress's domain. Unlike name it need not be unique, so
   * successive sandboxes can reuse one hostname (only one may be live
   * at a time). Defaults to <name>.<ingress domain>, then
   * <id>.<ingress domain>, when omitted.
   */
  domain?: string;
  /**
   * Which sandbox ingress serves the domain when the cluster has both a
   * public and a private one. Omit to default to whichever is
   * configured, public winning. Rejected when the sandbox exposes a
   * port but the requested ingress is not configured on the cluster.
   */
  visibility?: SandboxDomainSpecVisibility;
}

export interface SandboxEgressSpec {
  /**
   * Destinations the sandbox may reach; all other outbound traffic is
   * denied. An entry is a hostname (api.example.com), a wildcard
   * (*.example.com) matching any host under that domain but not the
   * domain itself, an IP literal, a CIDR range (203.0.113.0/24), or the
   * cluster-internal hostname of a Service on the sandbox's cluster
   * (name.namespace.svc.cluster.local), which allows the Service's
   * backing pods as they change. Enforcement is transparent at the
   * network layer, so any protocol and client works without proxy
   * configuration. An empty list denies all egress; omit egress entirely
   * to leave the sandbox's internet access unrestricted.
   */
  allowed_destinations: string[];
}

export interface SandboxMetricsPoint {
  /** Timestamp for the data point, in UTC. */
  timestamp_utc: string;
  /** Metric value at this timestamp. */
  value: number;
}

/** Time series for one sandbox metric over a range, shaped like the app metrics response so the dashboard reuses the same chart selectors. */
export interface SandboxMetricsResponse {
  /** One entry per query; this endpoint returns a single entry. */
  results: SandboxMetricsResult[];
}

export interface SandboxMetricsResult {
  /** One entry per Prometheus series, normally the single sandbox pod. */
  series: SandboxMetricsSeries[];
}

export interface SandboxMetricsSeries {
  /** Prometheus labels identifying the series. */
  labels?: Record<string, string>;
  /** Unit of the series values (e.g. cores, bytes, bytes/sec). */
  unit?: string;
  /** Data points in chronological order. */
  time_series: SandboxMetricsPoint[];
}

export interface SandboxNetworkingSpec {
  /**
   * Port the workload listens on; the per-sandbox Service targets it on
   * the pod. Privileged ports (1-1023) are not allowed.
   */
  port: number;
  /**
   * Domains the port is served on through a sandbox ingress. Omit to
   * serve the port at the default hostname through the default ingress.
   * Currently only one entry is supported.
   */
  domains?: SandboxDomainSpec[];
}

/**
 * CPU and memory for the sandbox, as Kubernetes quantities. An omitted
 * field keeps the cluster's default sandbox size for that resource. The
 * sandbox can use up to the given amount.
 */
export interface SandboxResourcesSpec {
  /** CPU cores, e.g. "2", "500m". */
  cpu?: string;
  /** Memory, e.g. "2Gi", "512Mi". */
  memory?: string;
}

export interface SandboxSpec {
  /**
   * Container image to run. Empty when snapshot_id is set, since the
   * snapshot is the image.
   */
  image: string;
  /**
   * Start the sandbox from this snapshot's filesystem instead of an image,
   * so image must be left unset. The snapshot carries no command or volumes:
   * an omitted command runs the base image's, and the sandbox mounts only
   * the volumes this request asks for.
   */
  snapshot_id?: string;
  /**
   * Sandbox name, unique within the cluster. Must be a valid DNS label
   * (lowercase alphanumeric and dashes). Defaults to the sandbox's id
   * when omitted.
   */
  name?: string;
  /** Arbitrary key/value labels for identifying and filtering sandboxes */
  tags?: Record<string, string>;
  /** Override image entrypoint */
  command?: string[];
  /** Arguments passed to the command */
  args?: string[];
  /** Environment variables to set in the sandbox, keyed by name */
  env?: Record<string, string>;
  /**
   * Names of environment groups on the cluster whose variables are
   * injected into the sandbox, resolved to their latest version at create
   * time. On a key conflict a later group wins over an earlier one, and
   * an explicit env entry wins over any group value.
   */
  env_groups?: string[];
  /**
   * Volumes to mount, keyed by the absolute mount path inside the
   * sandbox; values are volume IDs.
   */
  volume_mounts?: Record<string, string>;
  /**
   * Network exposure for the sandbox. Omit to expose nothing. Currently
   * only one entry is supported.
   */
  networking?: SandboxNetworkingSpec[];
  egress?: SandboxEgressSpec;
  resources?: SandboxResourcesSpec;
  /**
   * Maximum lifetime in seconds, counted from when the sandbox starts
   * running (from creation while it waits to start). The sandbox is
   * terminated once it elapses. Omit for no limit.
   */
  ttl_seconds?: number;
}

export interface Snapshot {
  /** Snapshot id */
  id: string;
  /** Sandbox the snapshot was captured from */
  sandbox_id: string;
  mode: SnapshotMode;
  /** Capture state. A sandbox can be started from a snapshot once it is ready. A failed capture keeps its record so the reason stays visible. */
  status: SnapshotStatus;
  /** When the capture started, in unix milliseconds */
  t_created_unix_ms?: number;
  /** When the capture completed, in unix milliseconds */
  t_ready_unix_ms?: number;
  /** Why the capture failed, when it did */
  failure_reason?: string;
  /** Total size of what was captured */
  size_bytes?: number;
}

export interface SnapshotListResponse {
  snapshots: Snapshot[];
}

export interface SnapshotSpec {
  /** What to capture. Defaults to capturing the filesystem. */
  mode?: SnapshotMode;
}

export interface StatusResponse {
  /** Sandbox ID */
  id: string;
  /** Sandbox name (the id when no name was given) */
  name: string;
  /** Image the sandbox runs */
  image: string;
  /** Tags the sandbox was created with */
  tags?: Record<string, string>;
  /** Current phase */
  phase: StatusResponsePhase;
  /** Exit code if completed */
  exit_code?: number | null;
  /** When the sandbox was created */
  created_at: string;
  /** When the sandbox pod started running */
  started_at?: string | null;
  /** When the sandbox reached a terminal phase (succeeded, failed, or terminated) */
  finished_at?: string | null;
  /**
   * Public hostname the sandbox is reachable at. Empty when the sandbox
   * exposes no port or the cluster has no sandbox ingress configured.
   */
  host: string;
  /** Volumes the sandbox mounts, keyed by mount path */
  volume_mounts?: Record<string, string>;
  /** Where a client addresses an interactive exec into the running sandbox. Absent until the sandbox has a pod. */
  exec_target?: ExecTarget;
}

export interface Volume {
  /**
   * Volume ID, assigned when the volume is created. All volume
   * operations address volumes by ID; the name is informational.
   */
  id: string;
  /** Volume name */
  name: string;
  /**
   * Kind of volume. A disk volume is persistent file storage owned by
   * the volume; an object volume exposes a registered bucket.
   */
  type: VolumeType;
  object?: VolumeObjectSpec;
  /**
   * Subdirectory, relative to the shared sandbox volumes mount, where this
   * volume's data lives. An app that mounts the cluster's sandbox volumes
   * reads this volume at <mount>/<path>. Empty for object volumes, which
   * read straight from their bucket.
   */
  path: string;
  /** Current lifecycle phase of the volume */
  phase: VolumePhase;
  /** IDs of sandboxes the volume is attached to */
  attached_to: string[];
  /** When the volume was created */
  created_at: string;
}

export interface VolumeFileEntry {
  /**
   * Entry name within its parent directory, without any path separator
   * (e.g. model.bin). Entries nest, so a directory name is carried once
   * on the directory itself rather than repeated in the path of every
   * entry beneath it. Reconstruct an entry's path relative to the volume
   * root by joining the names from the listing's path down to the entry.
   */
  name: string;
  /** Whether the entry is a regular file or a directory */
  type: VolumeFileEntryType;
  /** Size of the entry in bytes. Zero for directories. */
  size_bytes: number;
  /**
   * When the entry was last modified. Always set on files; may be absent
   * on directories when the volume's storage keeps no directory
   * modification time.
   */
  modified_at?: string;
  /**
   * Set on a directory entry whose contents the walk did not fully read:
   * the entry budget ran out before entering it, or the directory alone
   * holds more entries than the budget. List the directory directly to
   * read more of them. Never set on files.
   */
  truncated?: boolean;
  /**
   * Entries directly inside this directory, directories before files and
   * each group by name. Omitted on files, and on a directory whose
   * entries the walk did not read (which carries truncated instead).
   */
  entries?: VolumeFileEntry[];
}

export interface VolumeFileListResponse {
  /** The walked directory, relative to the volume root */
  path: string;
  /**
   * Entries directly inside the walked directory, directories before
   * files and each group by name. Entries nest, so everything the walk
   * read below this level hangs off these entries rather than appearing
   * here as a flat path.
   */
  entries: VolumeFileEntry[];
  /**
   * Whether the walk stopped at its entry budget before reading every
   * entry. Directories left unread or partially read carry their own
   * truncated marker.
   */
  truncated: boolean;
}

export interface VolumeFileMoveRequest {
  /**
   * File or directory to move, relative to the volume root, with or
   * without a leading slash. A directory moves with everything under it.
   */
  from: string;
  /**
   * Where to move it to, relative to the volume root, with or without a
   * leading slash. This is the entry's full new path rather than the
   * directory to place it in, so a move renames and relocates in one call.
   * The parent directory must already exist.
   */
  to: string;
}

export interface VolumeListResponse {
  /** All volumes in the cluster */
  volumes: Volume[];
}

export interface VolumeObjectSpec {
  /** Bucket the volume exposes. Must be registered on the cluster. */
  bucket: string;
  /**
   * Key prefix the volume is scoped to, without leading or trailing
   * slashes. Sandboxes see only objects under the prefix, at paths
   * relative to it. Omit to expose the whole bucket.
   */
  prefix?: string;
  /**
   * How sandboxes that attach the volume can use the bucket. read_only
   * forbids all writes; write_only_new_files allows only new objects, with no
   * overwrites or deletes of existing ones. Defaults to read_write. A
   * bucket registered with read_only accepts only read_only volumes.
   */
  access?: VolumeObjectSpecAccess;
}

export interface VolumeSpec {
  /**
   * Volume name, unique within the cluster. Must be a valid DNS label
   * (lowercase alphanumeric and dashes). Defaults to the volume's id
   * when omitted.
   */
  name?: string;
  /**
   * Kind of volume to create. A disk volume is persistent file storage
   * owned by the volume; an object volume exposes a bucket registered
   * on the cluster. Defaults to disk when omitted.
   */
  type?: VolumeSpecType;
  object?: VolumeObjectSpec;
}
