// Generated by oagen. DO NOT EDIT.


import type { FilterValuesResponsePhases, LogLineLevel, SandboxDomainSpecVisibility, StatusResponsePhase, VolumePhase } from './enums.js';

export interface CountPoint {
  /** Start of the bucket. */
  timestamp: string;
  /** Sandboxes created within the bucket. */
  count: number;
}

export interface CountResponse {
  /** Created-sandbox counts per bucket, oldest first, gap-free. */
  points: CountPoint[];
  /** Width of each bucket in milliseconds. */
  granularity_ms: number;
}

export interface CreateResponse {
  /** Sandbox ID */
  id: string;
  /** Sandbox name (the id when no name was given) */
  name: string;
  /** Volumes the sandbox mounts, keyed by mount path */
  volume_mounts?: Record<string, string>;
}

export interface Error {
  /** Error message */
  error: string;
}

export interface ExecRequest {
  /** Command and arguments to run in the sandbox */
  command: string[];
}

export interface ExecResponse {
  /** Captured standard output */
  stdout: string;
  /** Captured standard error */
  stderr: string;
  /** Command exit code. Non-zero is a normal result, not an error. */
  exit_code: number;
}

export interface ExecTarget {
  /** Namespace of the sandbox pod */
  namespace: string;
  /** Name of the sandbox pod */
  pod_name: string;
  /** Container to target. For warm sandboxes this is the pod's placeholder container, which the node redirects to the injected workload. */
  container_name: string;
}

export interface FilterValuesResponse {
  /** Distinct sandbox tags, formatted as key=value */
  tags: string[];
  /** Distinct sandbox images */
  images: string[];
  /** Supported sandbox phases */
  phases: FilterValuesResponsePhases[];
}

export interface HealthResponse {
  /** Health status */
  status: string;
}

export interface ListResponse {
  /** Matching sandboxes */
  sandboxes: StatusResponse[];
  pagination: Pagination;
  /** Cluster-wide filter option values, included only when requested. */
  filter_values?: FilterValuesResponse;
}

export interface LogLine {
  /** When the log line was emitted */
  timestamp: string;
  /** Log line content */
  line: string;
  /** Log severity level */
  level: LogLineLevel;
  /** ID of the exec that produced this line; empty when the line is the workload's own output */
  exec_id: string;
}

export interface LogsResponse {
  /** Sandbox ID */
  sandbox_id: string;
  /** Log lines */
  logs: LogLine[];
}

export interface LookupResult {
  /** The resolved resource id */
  id: string;
}

export interface Pagination {
  /** Current page number (1-based) */
  current_page: number;
  /** Total number of pages */
  total_pages: number;
  /** Whether there are more items after this page */
  has_next_page: boolean;
}

export interface ReadinessResponse {
  /** Readiness status */
  status: string;
  /** Number of active sandboxes */
  active_sandboxes: number;
}

export interface SandboxDomainSpec {
  /**
   * Fully qualified hostname for the sandbox, one label under the
   * target ingress's domain. Unlike name it need not be unique, so
   * successive sandboxes can reuse one hostname (only one may be live
   * at a time). Defaults to <name>.<ingress domain>, then
   * <id>.<ingress domain>, when omitted.
   */
  domain?: string;
  /**
   * Which sandbox ingress serves the domain when the cluster has both a
   * public and a private one. Omit to default to whichever is
   * configured, public winning. Rejected when the sandbox exposes a
   * port but the requested ingress is not configured on the cluster.
   */
  visibility?: SandboxDomainSpecVisibility;
}

export interface SandboxNetworkingSpec {
  /**
   * Port the workload listens on; the per-sandbox Service targets it on
   * the pod. Privileged ports (1-1023) are not allowed.
   */
  port: number;
  /**
   * Domains the port is served on through a sandbox ingress. Omit to
   * serve the port at the default hostname through the default ingress.
   * Currently only one entry is supported.
   */
  domains?: SandboxDomainSpec[];
}

export interface SandboxSpec {
  /** Container image to run */
  image: string;
  /**
   * Sandbox name, unique within the cluster. Must be a valid DNS label
   * (lowercase alphanumeric and dashes). Defaults to the sandbox's id
   * when omitted.
   */
  name?: string;
  /** Arbitrary key/value labels for identifying and filtering sandboxes */
  tags?: Record<string, string>;
  /** Override image entrypoint */
  command?: string[];
  /** Arguments passed to the command */
  args?: string[];
  /** Environment variables to set in the sandbox, keyed by name */
  env?: Record<string, string>;
  /**
   * Volumes to mount, keyed by the absolute mount path inside the
   * sandbox; values are volume IDs.
   */
  volume_mounts?: Record<string, string>;
  /**
   * Network exposure for the sandbox. Omit to expose nothing. Currently
   * only one entry is supported.
   */
  networking?: SandboxNetworkingSpec[];
}

export interface StatusResponse {
  /** Sandbox ID */
  id: string;
  /** Sandbox name (the id when no name was given) */
  name: string;
  /** Image the sandbox runs */
  image: string;
  /** Tags the sandbox was created with */
  tags?: Record<string, string>;
  /** Current phase */
  phase: StatusResponsePhase;
  /** Exit code if completed */
  exit_code?: number | null;
  /** When the sandbox was created */
  created_at: string;
  /** When the sandbox pod started running */
  started_at?: string | null;
  /**
   * Public hostname the sandbox is reachable at. Empty when the sandbox
   * exposes no port or the cluster has no sandbox ingress configured.
   */
  host: string;
  /** Volumes the sandbox mounts, keyed by mount path */
  volume_mounts?: Record<string, string>;
  /** Where a client addresses an interactive exec into the running sandbox. Absent until the sandbox has a pod. */
  exec_target?: ExecTarget;
}

export interface Volume {
  /**
   * Volume ID, assigned when the volume is created. All volume
   * operations address volumes by ID; the name is informational.
   */
  id: string;
  /** Volume name */
  name: string;
  /** Current lifecycle phase of the volume */
  phase: VolumePhase;
  /** IDs of sandboxes the volume is attached to */
  attached_to: string[];
  /** When the volume was created */
  created_at: string;
}

export interface VolumeListResponse {
  /** All volumes in the cluster */
  volumes: Volume[];
}

export interface VolumeSpec {
  /**
   * Volume name, unique within the cluster. Must be a valid DNS label
   * (lowercase alphanumeric and dashes). Defaults to the volume's id
   * when omitted.
   */
  name?: string;
}
