// Generated by oagen. DO NOT EDIT.


export const FilterValuesResponsePhases = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type FilterValuesResponsePhases = typeof FilterValuesResponsePhases[keyof typeof FilterValuesResponsePhases];

export const LogLineLevel = {
  Error: "error",
  Warning: "warning",
  Info: "info",
} as const;
export type LogLineLevel = typeof LogLineLevel[keyof typeof LogLineLevel];

export const SandboxDomainSpecVisibility = {
  Public: "public",
  Private: "private",
} as const;
export type SandboxDomainSpecVisibility = typeof SandboxDomainSpecVisibility[keyof typeof SandboxDomainSpecVisibility];

export const SandboxesPhase = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type SandboxesPhase = typeof SandboxesPhase[keyof typeof SandboxesPhase];

export const StatusResponsePhase = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type StatusResponsePhase = typeof StatusResponsePhase[keyof typeof StatusResponsePhase];

export const VolumePhase = {
  Pending: "pending",
  Ready: "ready",
  Failed: "failed",
} as const;
export type VolumePhase = typeof VolumePhase[keyof typeof VolumePhase];
