// Generated by oagen. DO NOT EDIT.


export const FilterValuesResponsePhases = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type FilterValuesResponsePhases = typeof FilterValuesResponsePhases[keyof typeof FilterValuesResponsePhases];

export const LogLineLevel = {
  Error: "error",
  Warning: "warning",
  Info: "info",
} as const;
export type LogLineLevel = typeof LogLineLevel[keyof typeof LogLineLevel];

export const SandboxDomainSpecVisibility = {
  Public: "public",
  Private: "private",
} as const;
export type SandboxDomainSpecVisibility = typeof SandboxDomainSpecVisibility[keyof typeof SandboxDomainSpecVisibility];

export const SandboxesPhase = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type SandboxesPhase = typeof SandboxesPhase[keyof typeof SandboxesPhase];

export const SandboxMetric = {
  CpuUsage: "cpu_usage",
  CpuReserved: "cpu_reserved",
  MemoryUsage: "memory_usage",
  MemoryReserved: "memory_reserved",
  NetworkRx: "network_rx",
  NetworkTx: "network_tx",
} as const;
export type SandboxMetric = typeof SandboxMetric[keyof typeof SandboxMetric];

export const SnapshotMode = {
  Filesystem: "filesystem",
  Full: "full",
} as const;
export type SnapshotMode = typeof SnapshotMode[keyof typeof SnapshotMode];

export const SnapshotStatus = {
  Pending: "pending",
  Ready: "ready",
  Failed: "failed",
} as const;
export type SnapshotStatus = typeof SnapshotStatus[keyof typeof SnapshotStatus];

export const StatusResponsePhase = {
  Queued: "queued",
  Creating: "creating",
  Running: "running",
  Succeeded: "succeeded",
  Failed: "failed",
  Terminated: "terminated",
} as const;
export type StatusResponsePhase = typeof StatusResponsePhase[keyof typeof StatusResponsePhase];

export const VolumeFileEntryType = {
  File: "file",
  Directory: "directory",
} as const;
export type VolumeFileEntryType = typeof VolumeFileEntryType[keyof typeof VolumeFileEntryType];

export const VolumeObjectSpecAccess = {
  ReadWrite: "read_write",
  ReadOnly: "read_only",
  WriteOnlyNewFiles: "write_only_new_files",
} as const;
export type VolumeObjectSpecAccess = typeof VolumeObjectSpecAccess[keyof typeof VolumeObjectSpecAccess];

export const VolumePhase = {
  Pending: "pending",
  Ready: "ready",
  Failed: "failed",
} as const;
export type VolumePhase = typeof VolumePhase[keyof typeof VolumePhase];

export const VolumeSpecType = {
  Disk: "disk",
  Object: "object",
} as const;
export type VolumeSpecType = typeof VolumeSpecType[keyof typeof VolumeSpecType];

export const VolumeType = {
  Disk: "disk",
  Object: "object",
} as const;
export type VolumeType = typeof VolumeType[keyof typeof VolumeType];
