// Generated by oagen. DO NOT EDIT.


import type { HealthResponse } from './_models.js';
import type { Healthz as HealthzResource } from './resources/healthz.js';

/** User-facing healthz namespace under `Porter`. */
export class Healthz {
  constructor(private readonly resource: HealthzResource) {}

  /** Direct access to the generated low-level healthz resource. */
  get raw(): HealthzResource {
    return this.resource;
  }

  async healthCheck(): Promise<HealthResponse> {
    return this.resource.healthCheck();
  }
}
