// Generated by oagen. DO NOT EDIT.


import type { ClientOptions } from './_baseClient.js';
import { PorterSandboxApiClient } from './_client.js';
import { Healthz } from './healthz.js';
import { Readyz } from './readyz.js';
import { Sandboxes } from './sandboxes.js';
import { Snapshots } from './snapshots.js';
import { Volumes } from './volumes.js';

/** Top-level Porter client. */
export class Porter {
  readonly healthz: Healthz;
  readonly readyz: Readyz;
  readonly sandboxes: Sandboxes;
  readonly snapshots: Snapshots;
  readonly volumes: Volumes;

  private readonly client: PorterSandboxApiClient;

  constructor(options: ClientOptions = {}) {
    this.client = new PorterSandboxApiClient(options);
    this.healthz = new Healthz(this.client.healthz);
    this.readyz = new Readyz(this.client.readyz);
    this.sandboxes = new Sandboxes(this.client.sandboxes);
    this.snapshots = new Snapshots(this.client.snapshots);
    this.volumes = new Volumes(this.client.volumes);
  }

  /** Direct access to the generated low-level API client. */
  get raw(): PorterSandboxApiClient {
    return this.client;
  }

  close(): void {
    this.client.close();
  }
}
