// Generated by oagen. DO NOT EDIT.


import type { ReadinessResponse } from './_models.js';
import type { Readyz as ReadyzResource } from './resources/readyz.js';

/** User-facing readyz namespace under `Porter`. */
export class Readyz {
  constructor(private readonly resource: ReadyzResource) {}

  /** Direct access to the generated low-level readyz resource. */
  get raw(): ReadyzResource {
    return this.resource;
  }

  async readinessCheck(): Promise<ReadinessResponse> {
    return this.resource.readinessCheck();
  }
}
