// Generated by oagen. DO NOT EDIT.


import type { SandboxSpec } from './_models.js';
import type { Sandboxes as SandboxesResource } from './resources/sandboxes.js';
import { Sandbox } from './sandbox.js';

/** User-facing sandboxes namespace under `Porter`. */
export class Sandboxes {
  constructor(private readonly resource: SandboxesResource) {}

  /** Direct access to the generated low-level sandboxes resource. */
  get raw(): SandboxesResource {
    return this.resource;
  }

  async create(spec: SandboxSpec): Promise<Sandbox> {
    const created = await this.resource.create(spec);
    return new Sandbox({ id: created.id, resource: this.resource });
  }

  async get(name: string): Promise<Sandbox> {
    const { id } = await this.resource.lookup({ name });
    const status = await this.resource.get(id);
    return new Sandbox({ id, resource: this.resource, status });
  }

  async list(options: { tags?: Record<string, string>; page?: number } = {}): Promise<Sandbox[]> {
    const tagFilter = options.tags
      ? Object.entries(options.tags).map(([k, v]) => `${k}=${v}`)
      : undefined;
    const response = await this.resource.list({ tag: tagFilter, page: options.page });
    return response.sandboxes.map(
      (status) => new Sandbox({ id: status.id, resource: this.resource, status }),
    );
  }
}
