// Generated by oagen. DO NOT EDIT.


import type { Snapshot, SnapshotListResponse, SnapshotSpec } from './_models.js';
import type { Snapshots as SnapshotsResource } from './resources/snapshots.js';

/** User-facing snapshots namespace under `Porter`. */
export class Snapshots {
  constructor(private readonly resource: SnapshotsResource) {}

  /** Direct access to the generated low-level snapshots resource. */
  get raw(): SnapshotsResource {
    return this.resource;
  }

  async create(id: string, body: SnapshotSpec): Promise<Snapshot> {
    return this.resource.create(id, body);
  }

  async list(options?: { sandboxId?: string }): Promise<SnapshotListResponse> {
    return this.resource.list(options);
  }

  async delete(id: string): Promise<void> {
    await this.resource.delete(id);
  }
}
