// Generated by oagen. DO NOT EDIT.


import type { Volume as VolumeRecord, VolumeFileEntry } from './_models.js';
import type { VolumeFileEntryType, VolumePhase } from './enums.js';
import type { Volumes as VolumesResource } from './resources/volumes.js';

// How much of a file one request of `stream` reads. Files are read through
// ranged requests, so this bounds how many bytes a caller holds at once.
const DEFAULT_CHUNK_BYTES = 8 * 1024 * 1024;

// Volume paths are relative to the volume root. Accept them with or without a
// leading slash, and hand the API the '/'-rooted form its listings echo back.
const normalizePath = (path: string): string => {
  const trimmed = path.replace(/^\/+/, '').replace(/\/+$/, '');
  return trimmed === '' ? '/' : `/${trimmed}`;
};

const joinPath = (parent: string, name: string): string =>
  parent === '/' ? `/${name}` : `${parent}/${name}`;

const byteRangeHeader = (offset: number, length: number | undefined): string =>
  length === undefined ? `bytes=${offset}-` : `bytes=${offset}-${offset + length - 1}`;

/** A file or directory inside a volume. */
export class VolumeFile {
  /** Entry name within its parent directory, without any path separator. */
  readonly name: string;
  /** Path relative to the volume root, e.g. `/models/config.json`. */
  readonly path: string;
  readonly type: VolumeFileEntryType;
  readonly sizeBytes: number;
  readonly modifiedAt: Date | null;
  /**
   * Set on a directory the server's listing walk did not fully read — it holds
   * more entries than one listing covers. `iterdir` reads these directly;
   * `listdir` leaves them for the caller to list.
   */
  readonly truncated: boolean;

  constructor(entry: VolumeFileEntry, parentPath: string) {
    this.name = entry.name;
    this.path = joinPath(parentPath, entry.name);
    this.type = entry.type;
    this.sizeBytes = entry.size_bytes;
    this.modifiedAt = entry.modified_at ? new Date(entry.modified_at) : null;
    this.truncated = entry.truncated ?? false;
  }

  get isDirectory(): boolean {
    return this.type === 'directory';
  }

  get isFile(): boolean {
    return this.type === 'file';
  }
}

// Rich handle for a single volume. Constructed by the Volumes namespace —
// users don't instantiate this directly. Holds a back-reference to the
// underlying generated resource so file and lifecycle operations don't need to
// be re-passed a client.
export class Volume {
  private record: VolumeRecord;
  private readonly resource: VolumesResource;

  constructor(args: { record: VolumeRecord; resource: VolumesResource }) {
    this.record = args.record;
    this.resource = args.resource;
  }

  get id(): string {
    return this.record.id;
  }

  get name(): string {
    return this.record.name;
  }

  get phase(): VolumePhase {
    return this.record.phase;
  }

  /**
   * Subdirectory, relative to the shared sandbox volumes mount, where this
   * volume's data lives. An app that mounts the cluster's sandbox volumes
   * reads this volume at `<mount>/<path>`.
   */
  get path(): string {
    return this.record.path;
  }

  /** IDs of the sandboxes the volume is attached to. */
  get attachedTo(): string[] {
    return this.record.attached_to;
  }

  get createdAt(): Date {
    return new Date(this.record.created_at);
  }

  async refresh(): Promise<VolumeRecord> {
    this.record = await this.resource.get(this.id);
    return this.record;
  }

  /** Delete the volume. Fails while it is attached to a sandbox. */
  async delete(): Promise<void> {
    await this.resource.delete(this.id);
  }

  /** The entries directly inside `path`, directories first and each group by name. */
  async listdir(path = '/'): Promise<VolumeFile[]> {
    const parent = normalizePath(path);
    const listing = await this.resource.listFiles(this.id, { path: parent });
    return listing.entries.map((entry) => new VolumeFile(entry, parent));
  }

  /**
   * Every entry under `path`, depth-first. One listing covers a bounded number
   * of entries, so directories it left unread are listed as the walk reaches
   * them — a large tree costs more than one request.
   */
  async *iterdir(path = '/'): AsyncGenerator<VolumeFile> {
    const parent = normalizePath(path);
    const listing = await this.resource.listFiles(this.id, { path: parent });
    yield* this.walkEntries(parent, listing.entries, true);
  }

  /**
   * Entries under `path` whose name contains `query`, case-insensitively. The
   * search runs inside one listing walk, so a tree too large for a single
   * listing is searched as far as that walk reached.
   */
  async search(query: string, options: { path?: string } = {}): Promise<VolumeFile[]> {
    const parent = normalizePath(options.path ?? '/');
    const listing = await this.resource.listFiles(this.id, { path: parent, search: query });
    const needle = query.toLowerCase();
    // The API prunes the tree to matches plus the directories holding them;
    // keep only the entries that match so callers get the hits alone.
    const matches: VolumeFile[] = [];
    for await (const file of this.walkEntries(parent, listing.entries, false)) {
      if (file.name.toLowerCase().includes(needle)) matches.push(file);
    }
    return matches;
  }

  /**
   * Read a file's bytes. `offset` and `length` read a slice of it instead of
   * the whole file.
   */
  async readFile(path: string, options: { offset?: number; length?: number } = {}): Promise<Uint8Array> {
    const ranged = options.offset !== undefined || options.length !== undefined;
    const content = await this.resource.readFile(this.id, {
      path: normalizePath(path),
      range: ranged ? byteRangeHeader(options.offset ?? 0, options.length) : undefined,
    });
    return content.bytes;
  }

  /** Read a file as UTF-8 text. */
  async readText(path: string, options: { offset?: number; length?: number } = {}): Promise<string> {
    return new TextDecoder().decode(await this.readFile(path, options));
  }

  /**
   * Write bytes to a file, and create parent directories as needed. The file
   * appears at `path` only after the last byte, so an interrupted write leaves
   * the previous content in place.
   */
  async writeFile(path: string, content: Uint8Array): Promise<void> {
    await this.resource.writeFile(this.id, content, { path: normalizePath(path) });
  }

  /** Write UTF-8 text to a file. See {@link writeFile}. */
  async writeText(path: string, content: string): Promise<void> {
    await this.writeFile(path, new TextEncoder().encode(content));
  }

  /**
   * Move or rename a file or directory, where `to` is the full new path of the
   * entry. An occupied destination fails and leaves the entry where it was.
   */
  async moveFile(from: string, to: string): Promise<void> {
    await this.resource.moveFile(this.id, { from: normalizePath(from), to: normalizePath(to) });
  }

  /**
   * Read a file in chunks, so a large one never lands in memory whole. Each
   * chunk is its own ranged request.
   */
  async *stream(path: string, options: { chunkSize?: number } = {}): AsyncGenerator<Uint8Array> {
    const chunkSize = options.chunkSize ?? DEFAULT_CHUNK_BYTES;
    const filePath = normalizePath(path);
    let offset = 0;

    for (;;) {
      const content = await this.resource.readFile(this.id, {
        path: filePath,
        range: byteRangeHeader(offset, chunkSize),
      });
      if (content.bytes.length > 0) yield content.bytes;

      // An empty file comes back whole, with no Content-Range to page from.
      const range = content.contentRange;
      if (!range) return;

      offset = range.end + 1;
      if (offset >= range.size) return;
    }
  }

  // Depth-first over a listing's nested entries. `followTruncated` lists the
  // directories the server's walk left unread, which `iterdir` wants and
  // `search` does not: listing one of those directly would drop the search
  // term and pull in everything under it.
  private async *walkEntries(
    parent: string,
    entries: VolumeFileEntry[],
    followTruncated: boolean,
  ): AsyncGenerator<VolumeFile> {
    for (const entry of entries) {
      const file = new VolumeFile(entry, parent);
      yield file;
      if (!file.isDirectory) continue;
      if (entry.entries) {
        yield* this.walkEntries(file.path, entry.entries, followTruncated);
      } else if (file.truncated && followTruncated) {
        yield* this.iterdir(file.path);
      }
    }
  }
}
