// Generated by oagen. DO NOT EDIT.


import type { VolumeSpec } from './_models.js';
import type { Volumes as VolumesResource } from './resources/volumes.js';
import { type ObjectVolume, type Volume, wrapVolume } from './volume.js';

/** User-facing volumes namespace under `Porter`. */
export class Volumes {
  constructor(private readonly resource: VolumesResource) {}

  /** Direct access to the generated low-level volumes resource. */
  get raw(): VolumesResource {
    return this.resource;
  }

  async create(body: VolumeSpec): Promise<Volume | ObjectVolume> {
    const record = await this.resource.create(body);
    return wrapVolume({ record, resource: this.resource });
  }

  async list(): Promise<Array<Volume | ObjectVolume>> {
    const response = await this.resource.list();
    return response.volumes.map((record) => wrapVolume({ record, resource: this.resource }));
  }

  async get(name: string): Promise<Volume | ObjectVolume> {
    const { id } = await this.resource.lookup({ name });
    const record = await this.resource.get(id);
    return wrapVolume({ record, resource: this.resource });
  }

  async delete(name: string): Promise<void> {
    const { id } = await this.resource.lookup({ name });
    await this.resource.delete(id);
  }
}
