// Generated by oagen. DO NOT EDIT.


import type { Volume, VolumeListResponse, VolumeSpec } from './_models.js';
import type { Volumes as VolumesResource } from './resources/volumes.js';

/** User-facing volumes namespace under `Porter`. */
export class Volumes {
  constructor(private readonly resource: VolumesResource) {}

  /** Direct access to the generated low-level volumes resource. */
  get raw(): VolumesResource {
    return this.resource;
  }

  async create(body: VolumeSpec): Promise<Volume> {
    return this.resource.create(body);
  }

  async list(): Promise<VolumeListResponse> {
    return this.resource.list();
  }

  async get(name: string): Promise<Volume> {
    const { id } = await this.resource.lookup({ name });
    return this.resource.get(id);
  }

  async delete(name: string): Promise<void> {
    const { id } = await this.resource.lookup({ name });
    await this.resource.delete(id);
  }
}
